name: l
description: >
  Crossplatform html/io [L]ogger library with simple API.
  Manipulate with native console and store logs in txt files and indexedDB.
version: 0.1.0
#author: Plague Fox <Plugfox@gmail.com>
homepage: https://github.com/plugfox/l

#publish_to: 'none' 

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: any

dependency_overrides:
