name: l
description: >
  Cross-platform html/io Logger library with simple API.
  Manipulate with native and web console.
  Support ascii colorize output.
version: 3.0.0-nullsafety.1
repository: https://github.com/plugfox/l/tree/master
issue_tracker: https://github.com/plugfox/l/issues
homepage: https://github.com/plugfox/l
#author: Plague Fox <Plugfox@gmail.com>
#documentation: https://pub.dev/documentation/l/latest

#publish_to: 'none' 

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  coverage: ^1.0.0
  test: ^1.16.6

#dependency_overrides:
