name: l
description: >
  Cross-platform html/io Logger library with simple API.
  Manipulate with native console and store logs in txt files and indexedDB.
  Support ascii colorize output.
version: 2.0.0-dev
repository: https://github.com/plugfox/l/tree/master
issue_tracker: https://github.com/plugfox/l/issues
homepage: https://github.com/plugfox/l
#author: Plague Fox <Plugfox@gmail.com>
#documentation: https://pub.dev/documentation/l/latest

#publish_to: 'none' 

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: '>=1.0.0 <2.0.0'

dev_dependencies:
  test_coverage: ^0.4.3
  test: ^1.15.3

#dependency_overrides:
